site_name: Fates List Docs
site_url: https://fateslist.xyz
repo_name: GitHub
repo_url: https://github.com/Fates-List/FatesList
remote_branch: main
edit_uri: edit/main/docs/docs
theme:
        name: material
        logo: https://fateslist.xyz/static/botlisticon.webp
        palette:
                primary: black
        features:
                - navigation.sections
                - navigation.tabs
markdown_extensions:
        - admonition
        - pymdownx.superfences
plugins:
        - git-revision-date
        - git-revision-date-localized
